cleanup changes if aborted manually with ctrl+c

diff --git a/cask-repair b/cask-repair
--- a/cask-repair
+++ b/cask-repair
@@ -35,6 +35,9 @@ finish() {
   fi
 }
 
+# cleanup if aborted with ⌃C
+trap 'finish abort "You decided to abort"' SIGINT
+
 # define divider function
 divide() {
   if [[ $(which hr) ]]; then
