Default output to current directory

diff --git a/extract-app-icon b/extract-app-icon
--- a/extract-app-icon
+++ b/extract-app-icon
@@ -7,13 +7,18 @@ function get_output_path {
   local -r input_path="${2}"
   local output_path="${3}"
 
+  if [[ ! -d "$(dirname "${output_path}")" ]]; then
+    echo "Cannot create '${output_path}'. Parent directory does not exist." >&2
+    exit 1
+  fi
+
   if [[ -n "${output_path}" ]]; then
-    [[ "${output_path##*.}" == "${ext}" ]] && echo "${output_path}" || echo "${output_path}.${ext}"
+    [[ "${output_path##*.}" == "${ext}" ]] && echo "${output_path}" || echo "${output_path}${ext}"
   else
-    output_path="${input_path%.*}.${ext}"
+    output_path="$(pwd -P)/$(basename "${input_path%.*}${ext}")"
 
     while [[ -e "${output_path}" ]]; do
-      output_path="${output_path%.*}_$(date -u +'%Y.%m.%d.%H%M%S').${ext}"
+      output_path="${output_path%.*}_$(date -u +'%Y.%m.%d.%H%M%S')${ext}"
     done
 
     echo "${output_path}"
@@ -33,7 +38,7 @@ function usage {
       ${program} [options] <file>
 
     Options:
-      -o, --output-file <file>   File to output to. Default is saving next to the input app with same name.
+      -o, --output-file <file>   File to output to. Default is with same name on current directory.
       -h, --help                 Show this message.
   " | sed -E 's/^ {4}//'
 }
@@ -77,7 +82,7 @@ done
 set -- "${args[@]}"
 
 readonly input_app="${1}"
-readonly output_file="$(get_output_path 'png' "${input_app}" "${given_output_path}")"
+readonly output_file="$(get_output_path '.png' "${input_app}" "${given_output_path}")"
 readonly app_icon_name="$(get_app_key 'CFBundleIconFile' "${input_app}" | sed 's/\.icns$//')"
 readonly resources_dir="${input_app}/Contents/Resources"
 readonly icns="${resources_dir}/${app_icon_name}.icns"
diff --git a/gfv b/gfv
--- a/gfv
+++ b/gfv
@@ -22,13 +22,18 @@ function get_output_path {
   local -r input_path="${2}"
   local output_path="${3}"
 
+  if [[ ! -d "$(dirname "${output_path}")" ]]; then
+    echo "Cannot create '${output_path}'. Parent directory does not exist." >&2
+    exit 1
+  fi
+
   if [[ -n "${output_path}" ]]; then
-    [[ "${output_path##*.}" == "${ext}" ]] && echo "${output_path}" || echo "${output_path}.${ext}"
+    [[ "${output_path##*.}" == "${ext}" ]] && echo "${output_path}" || echo "${output_path}${ext}"
   else
-    output_path="${input_path%.*}.${ext}"
+    output_path="$(pwd -P)/$(basename "${input_path%.*}${ext}")"
 
     while [[ -e "${output_path}" ]]; do
-      output_path="${output_path%.*}_$(date -u +'%Y.%m.%d.%H%M%S').${ext}"
+      output_path="${output_path%.*}_$(date -u +'%Y.%m.%d.%H%M%S')${ext}"
     done
 
     echo "${output_path}"
@@ -43,7 +48,7 @@ function usage {
     Options:
       -f <integer>, --fps <integer>          Frames per second. Default is auto-detected from video, capped at ${cap_fps}.
       -w <interger>, --width <integer>       Resize the gif proportionally.
-      -o, --output-file <file>               File to output to. Default is saving next to the input file with same name.
+      -o <file>, --output-file <file>        File to output to. Default is with same name on current directory.
       -g, --gifski                           Use gifski for the conversion.
       -h, --help                             Show this help.
   " | sed -E 's/^ {4}//'
@@ -90,7 +95,7 @@ done
 set -- "${args[@]}"
 
 readonly input_file="${1}"
-readonly output_file="$(get_output_path 'gif' "${input_file}" "${given_output_path}")"
+readonly output_file="$(get_output_path '.gif' "${input_file}" "${given_output_path}")"
 
 if [[ "${#}" -ne 1 || ! -f "${input_file}" ]]; then
   usage
diff --git a/makeicns b/makeicns
--- a/makeicns
+++ b/makeicns
@@ -7,13 +7,18 @@ function get_output_path {
   local -r input_path="${2}"
   local output_path="${3}"
 
+  if [[ ! -d "$(dirname "${output_path}")" ]]; then
+    echo "Cannot create '${output_path}'. Parent directory does not exist." >&2
+    exit 1
+  fi
+
   if [[ -n "${output_path}" ]]; then
-    [[ "${output_path##*.}" == "${ext}" ]] && echo "${output_path}" || echo "${output_path}.${ext}"
+    [[ "${output_path##*.}" == "${ext}" ]] && echo "${output_path}" || echo "${output_path}${ext}"
   else
-    output_path="${input_path%.*}.${ext}"
+    output_path="$(pwd -P)/$(basename "${input_path%.*}${ext}")"
 
     while [[ -e "${output_path}" ]]; do
-      output_path="${output_path%.*}_$(date -u +'%Y.%m.%d.%H%M%S').${ext}"
+      output_path="${output_path%.*}_$(date -u +'%Y.%m.%d.%H%M%S')${ext}"
     done
 
     echo "${output_path}"
@@ -33,7 +38,7 @@ function usage {
       ${program} [options] <file>
 
     Options:
-      -o, --output-file <file>   File to output to. Default is saving next to the input file with same name.
+      -o, --output-file <file>   File to output to. Default is with same name on current directory.
       -h, --help                 Show this message.
   " | sed -E 's/^ {4}//'
 }
@@ -67,7 +72,7 @@ done
 set -- "${args[@]}"
 
 readonly input_file="${1}"
-readonly output_file="$(get_output_path 'icns' "${input_file}" "${given_output_path}")"
+readonly output_file="$(get_output_path '.icns' "${input_file}" "${given_output_path}")"
 readonly iconset="$(mktemp -d)"
 
 if [[ "${#}" -ne 1 || ! -f "${input_file}" ]]; then
diff --git a/pkg-extract b/pkg-extract
--- a/pkg-extract
+++ b/pkg-extract
@@ -24,15 +24,26 @@ function absolute_path {
   fi
 }
 
-function get_output_dir {
-  local -r input_path="${1}"
-  local -r output_dir="${2}"
+function get_output_path {
+  local -r ext="${1}"
+  local -r input_path="${2}"
+  local output_path="${3}"
 
-  if [[ -n "${output_dir}" ]]; then
-    mkdir -p "${output_dir}"
-    absolute_path "${output_dir}"
+  if [[ ! -d "$(dirname "${output_path}")" ]]; then
+    echo "Cannot create '${output_path}'. Parent directory does not exist." >&2
+    exit 1
+  fi
+
+  if [[ -n "${output_path}" ]]; then
+    [[ "${output_path##*.}" == "${ext}" ]] && echo "${output_path}" || echo "${output_path}${ext}"
   else
-    absolute_path "$(dirname "${input_path}")"
+    output_path="$(pwd -P)/$(basename "${input_path%.*}${ext}")"
+
+    while [[ -e "${output_path}" ]]; do
+      output_path="${output_path%.*}_$(date -u +'%Y.%m.%d.%H%M%S')${ext}"
+    done
+
+    echo "${output_path}"
   fi
 }
 
@@ -44,7 +55,7 @@ function usage {
       ${program} [options] <path_to_pkg>
 
     Options:
-      -o, --output-dir <dir>   Directory to extract to. Defaults to the same directory as the input pkg.
+      -o, --output-dir <dir>   Directory to extract to. Default is with same name on current directory. Appends '.extracted' to the name.
       -h, --help               Show this message.
   " | sed -E 's/^ {4}//'
 }
@@ -77,8 +88,8 @@ done
 set -- "${args[@]}"
 
 readonly input_pkg="${1}"
-readonly extract_dir="$(mktemp -d)/$(basename "${input_pkg}.extracted")"
-readonly output_dir="$(get_output_dir "${input_pkg}" "${given_output_path}")"
+readonly extract_dir="$(mktemp -d)/extracted_pkg"
+readonly output_dir="$(get_output_path '.extracted' "${input_pkg}" "${given_output_path}")"
 
 if [[ "${#}" -ne 1 || "$(file --brief --mime-type "${input_pkg}")" != 'application/x-xar' ]]; then
   usage
diff --git a/ringtonemaker b/ringtonemaker
--- a/ringtonemaker
+++ b/ringtonemaker
@@ -21,13 +21,18 @@ function get_output_path {
   local -r input_path="${2}"
   local output_path="${3}"
 
+  if [[ ! -d "$(dirname "${output_path}")" ]]; then
+    echo "Cannot create '${output_path}'. Parent directory does not exist." >&2
+    exit 1
+  fi
+
   if [[ -n "${output_path}" ]]; then
-    [[ "${output_path##*.}" == "${ext}" ]] && echo "${output_path}" || echo "${output_path}.${ext}"
+    [[ "${output_path##*.}" == "${ext}" ]] && echo "${output_path}" || echo "${output_path}${ext}"
   else
-    output_path="${input_path%.*}.${ext}"
+    output_path="$(pwd -P)/$(basename "${input_path%.*}${ext}")"
 
     while [[ -e "${output_path}" ]]; do
-      output_path="${output_path%.*}_$(date -u +'%Y.%m.%d.%H%M%S').${ext}"
+      output_path="${output_path%.*}_$(date -u +'%Y.%m.%d.%H%M%S')${ext}"
     done
 
     echo "${output_path}"
@@ -41,7 +46,7 @@ function usage {
 
     Options:
       -d <number>, --duration <number>   Duration (in seconds) of the output file. Maximum is 40 seconds.
-      -o <file>, --output <file>         Path to output file. If empty, will be next to the input file.
+      -o <file>, --output <file>         File to output to. Default is with same name on current directory.
       -s <time>, --start <time>          Start time from when to start cutting, in the form xx:xx:xx
       -h, --help                         Show this help.
   " | sed -E 's/^ {4}//'
@@ -86,7 +91,7 @@ set -- "${args[@]}"
 depends_on 'ffmpeg'
 
 readonly input_file="${1}"
-readonly output_file="$(get_output_path 'm4r' "${input_file}" "${given_output_path}")"
+readonly output_file="$(get_output_path '.m4r' "${input_file}" "${given_output_path}")"
 
 if [[ "${#}" -ne 1 || ! -f "${input_file}" ]]; then
   usage
