New function to try overwrite path

diff --git a/extract-app-icon b/extract-app-icon
--- a/extract-app-icon
+++ b/extract-app-icon
@@ -3,33 +3,33 @@
 readonly program="$(basename "${0}")"
 
 function get_output_path {
+  local -r ext="${1}"
+  local -r input_path="${2}"
+  local -r init_output_path="${3}"
+
+  if [[ -n "${init_output_path}" ]]; then
+    [[ "${init_output_path##*.}" == "${ext}" ]] && echo "${init_output_path}" || echo "${init_output_path}${ext}"
+  else
+    echo "$(pwd -P)/$(basename "${input_path%.*}${ext}")"
+  fi
+}
+
+function try_overwrite {
   local -r force="${1}"
-  local -r ext="${2}"
-  local -r input_path="${3}"
-  local -r init_output_path="${4}"
-
-  local -r output_path="$(
-    if [[ -n "${init_output_path}" ]]; then
-      [[ "${init_output_path##*.}" == "${ext}" ]] && echo "${init_output_path}" || echo "${init_output_path}${ext}"
-    else
-      echo "$(pwd -P)/$(basename "${input_path%.*}${ext}")"
-    fi
-  )"
-
-  echo "${output_path}"
+  local -r input_path="${2}"
 
   if [[ "${force}" == 'true' ]]; then
-    mkdir -p "$(dirname "${output_path}")"
+    mkdir -p "$(dirname "${input_path}")"
     return 0
   fi
 
-  if [[ ! -d "$(dirname "${output_path}")" ]]; then
-    echo "Cannot create '${output_path}'. Parent directory does not exist." >&2
+  if [[ ! -d "$(dirname "${input_path}")" ]]; then
+    echo "Cannot create '${input_path}'. Parent directory does not exist." >&2
     exit 1
   fi
 
-  if [[ -e "${output_path}" ]]; then
-    echo "Cannot write to '${output_path}'. Already exists." >&2
+  if [[ -e "${input_path}" ]]; then
+    echo "Cannot write to '${input_path}'. Already exists." >&2
     exit 1
   fi
 }
@@ -95,10 +95,11 @@ done
 set -- "${args[@]}"
 
 readonly input_app="${1}"
-readonly output_file="$(get_output_path "${overwrite:-false}" '.png' "${input_app}" "${given_output_path}")"
 readonly app_icon_name="$(get_app_key 'CFBundleIconFile' "${input_app}" | sed 's/\.icns$//')"
 readonly resources_dir="${input_app}/Contents/Resources"
 readonly icns="${resources_dir}/${app_icon_name}.icns"
+readonly output_file="$(get_output_path '.png' "${input_app}" "${given_output_path}")"
+try_overwrite "${overwrite:-false}" "${output_file}"
 
 if [[ "${#}" -ne 1 || ! -d "${input_app}" || "${input_app}" != *'.app' ]]; then
   echo 'An app bundle needs to be given as input' >&2
diff --git a/pkg-extract b/pkg-extract
--- a/pkg-extract
+++ b/pkg-extract
@@ -27,24 +27,37 @@ function absolute_path {
 function get_output_path {
   local -r ext="${1}"
   local -r input_path="${2}"
-  local output_path="${3}"
+  local -r init_output_path="${3}"
 
-  if [[ ! -d "$(dirname "${output_path}")" ]]; then
-    echo "Cannot create '${output_path}'. Parent directory does not exist." >&2
+  if [[ -n "${init_output_path}" ]]; then
+    [[ "${init_output_path##*.}" == "${ext}" ]] && echo "${init_output_path}" || echo "${init_output_path}${ext}"
+  else
+    echo "$(pwd -P)/$(basename "${input_path%.*}${ext}")"
+  fi
+}
+
+function try_overwrite {
+  local -r force="${1}"
+  local -r input_path="${2}"
+
+  if [[ "${force}" == 'true' ]]; then
+    mkdir -p "$(dirname "${input_path}")"
+    return 0
+  fi
+
+  if [[ ! -d "$(dirname "${input_path}")" ]]; then
+    echo "Cannot create '${input_path}'. Parent directory does not exist." >&2
     exit 1
   fi
 
-  if [[ -n "${output_path}" ]]; then
-    [[ "${output_path##*.}" == "${ext}" ]] && echo "${output_path}" || echo "${output_path}${ext}"
-  else
-    output_path="$(pwd -P)/$(basename "${input_path%.*}${ext}")"
-
-    while [[ -e "${output_path}" ]]; do
-      output_path="${output_path%.*}_$(date -u +'%Y.%m.%d.%H%M%S')${ext}"
-    done
-
-    echo "${output_path}"
+  if [[ -e "${input_path}" ]]; then
+    echo "Cannot write to '${input_path}'. Already exists." >&2
+    exit 1
   fi
+}
+
+function remove_pkg_extension {
+  sed -E 's/\.m?pkg$//' <<< "${1}"
 }
 
 function usage {
@@ -55,7 +68,7 @@ function usage {
       ${program} [options] <path_to_pkg>
 
     Options:
-      -o, --output-dir <dir>   Directory to extract to. Default is with same name on current directory. Appends '.extracted' to the name.
+      -o, --output-dir <dir>   Directory to extract to. Default is with same name on current directory. '.(m)pkg' will be removed from the end.
       -h, --help               Show this message.
   " | sed -E 's/^ {4}//'
 }
@@ -89,7 +102,8 @@ set -- "${args[@]}"
 
 readonly input_pkg="${1}"
 readonly extract_dir="$(mktemp -d)/extracted_pkg"
-readonly output_dir="$(get_output_path '.extracted' "${input_pkg}" "${given_output_path}")"
+readonly output_dir="$(get_output_path '' "${input_pkg}" "$(remove_pkg_extension "${given_output_path}")")"
+try_overwrite 'false' "${output_dir}" # If target directory exists, exit
 
 if [[ "${#}" -ne 1 || "$(file --brief --mime-type "${input_pkg}")" != 'application/x-xar' ]]; then
   usage
@@ -110,7 +124,7 @@ while IFS= read -r -d '' payload; do
 done < <(find "${extract_dir}" -type f -name 'Payload' -print0)
 
 while IFS= read -r -d '' pkg; do
-  mv "${pkg}" "${pkg}.extracted"
+  mv "${pkg}" "$(remove_pkg_extension "${pkg}")"
 done < <(find "${extract_dir}" -type d -name '*.pkg' -print0)
 
 mv "${extract_dir}" "${output_dir}"
