Add overwrite option

diff --git a/makeicns b/makeicns
--- a/makeicns
+++ b/makeicns
@@ -3,25 +3,34 @@
 readonly program="$(basename "${0}")"
 
 function get_output_path {
-  local -r ext="${1}"
-  local -r input_path="${2}"
-  local output_path="${3}"
+  local -r force="${1}"
+  local -r ext="${2}"
+  local -r input_path="${3}"
+  local -r init_output_path="${4}"
+
+  local -r output_path="$(
+    if [[ -n "${init_output_path}" ]]; then
+      [[ "${init_output_path##*.}" == "${ext}" ]] && echo "${init_output_path}" || echo "${init_output_path}${ext}"
+    else
+      echo "$(pwd -P)/$(basename "${input_path%.*}${ext}")"
+    fi
+  )"
+
+  echo "${output_path}"
+
+  if [[ "${force}" == 'true' ]]; then
+    mkdir -p "$(dirname "${output_path}")"
+    return 0
+  fi
 
   if [[ ! -d "$(dirname "${output_path}")" ]]; then
     echo "Cannot create '${output_path}'. Parent directory does not exist." >&2
     exit 1
   fi
 
-  if [[ -n "${output_path}" ]]; then
-    [[ "${output_path##*.}" == "${ext}" ]] && echo "${output_path}" || echo "${output_path}${ext}"
-  else
-    output_path="$(pwd -P)/$(basename "${input_path%.*}${ext}")"
-
-    while [[ -e "${output_path}" ]]; do
-      output_path="${output_path%.*}_$(date -u +'%Y.%m.%d.%H%M%S')${ext}"
-    done
-
-    echo "${output_path}"
+  if [[ -e "${output_path}" ]]; then
+    echo "Cannot write to '${output_path}'. Already exists." >&2
+    exit 1
   fi
 }
 
@@ -39,6 +48,7 @@ function usage {
 
     Options:
       -o, --output-file <file>   File to output to. Default is with same name on current directory.
+      -O, --overwrite            Create intermediary directories and overwrite output.
       -h, --help                 Show this message.
   " | sed -E 's/^ {4}//'
 }
@@ -54,6 +64,9 @@ while [[ "${1}" ]]; do
     -o | --output-file)
       readonly given_output_path="${2}"
       shift
+      ;;
+    -O | --overwrite)
+      readonly overwrite='true'
       ;;
     --)
       shift
@@ -72,7 +85,7 @@ done
 set -- "${args[@]}"
 
 readonly input_file="${1}"
-readonly output_file="$(get_output_path '.icns' "${input_file}" "${given_output_path}")"
+readonly output_file="$(get_output_path "${overwrite:-false}" '.icns' "${input_file}" "${given_output_path}")"
 readonly iconset="$(mktemp -d)"
 
 if [[ "${#}" -ne 1 || ! -f "${input_file}" ]]; then
diff --git a/ringtonemaker b/ringtonemaker
--- a/ringtonemaker
+++ b/ringtonemaker
@@ -17,25 +17,34 @@ function syntax_error {
 }
 
 function get_output_path {
-  local -r ext="${1}"
-  local -r input_path="${2}"
-  local output_path="${3}"
+  local -r force="${1}"
+  local -r ext="${2}"
+  local -r input_path="${3}"
+  local -r init_output_path="${4}"
+
+  local -r output_path="$(
+    if [[ -n "${init_output_path}" ]]; then
+      [[ "${init_output_path##*.}" == "${ext}" ]] && echo "${init_output_path}" || echo "${init_output_path}${ext}"
+    else
+      echo "$(pwd -P)/$(basename "${input_path%.*}${ext}")"
+    fi
+  )"
+
+  echo "${output_path}"
+
+  if [[ "${force}" == 'true' ]]; then
+    mkdir -p "$(dirname "${output_path}")"
+    return 0
+  fi
 
   if [[ ! -d "$(dirname "${output_path}")" ]]; then
     echo "Cannot create '${output_path}'. Parent directory does not exist." >&2
     exit 1
   fi
 
-  if [[ -n "${output_path}" ]]; then
-    [[ "${output_path##*.}" == "${ext}" ]] && echo "${output_path}" || echo "${output_path}${ext}"
-  else
-    output_path="$(pwd -P)/$(basename "${input_path%.*}${ext}")"
-
-    while [[ -e "${output_path}" ]]; do
-      output_path="${output_path%.*}_$(date -u +'%Y.%m.%d.%H%M%S')${ext}"
-    done
-
-    echo "${output_path}"
+  if [[ -e "${output_path}" ]]; then
+    echo "Cannot write to '${output_path}'. Already exists." >&2
+    exit 1
   fi
 }
 
@@ -46,7 +55,8 @@ function usage {
 
     Options:
       -d <number>, --duration <number>   Duration (in seconds) of the output file. Maximum is 40 seconds.
-      -o <file>, --output <file>         File to output to. Default is with same name on current directory.
+      -o <file>, --output-file <file>    File to output to. Default is with same name on current directory.
+      -O, --overwrite                    Create intermediary directories and overwrite output.
       -s <time>, --start <time>          Start time from when to start cutting, in the form xx:xx:xx
       -h, --help                         Show this help.
   " | sed -E 's/^ {4}//'
@@ -64,9 +74,12 @@ while [[ "${1}" ]]; do
       duration="${2}"
       shift
       ;;
-    -o | --output)
+    -o | --output-file)
       given_output_path="${2}"
       shift
+      ;;
+    -O | --overwrite)
+      readonly overwrite='true'
       ;;
     -s | --start)
       start="${2}"
@@ -91,7 +104,7 @@ set -- "${args[@]}"
 depends_on 'ffmpeg'
 
 readonly input_file="${1}"
-readonly output_file="$(get_output_path '.m4r' "${input_file}" "${given_output_path}")"
+readonly output_file="$(get_output_path "${overwrite:-false}" '.m4r' "${input_file}" "${given_output_path}")"
 
 if [[ "${#}" -ne 1 || ! -f "${input_file}" ]]; then
   usage
