Use depends_on that checks for multiple without red text

diff --git a/progressbar b/progressbar
--- a/progressbar
+++ b/progressbar
@@ -26,16 +26,12 @@ function depends_on {
   local missing_deps=()
 
   for dep in "${all_deps[@]}"; do
-    if ! command -v "${dep}" &>/dev/null; then
-      missing_deps+=("${dep}")
-    fi
+    command -v "${dep}" &>/dev/null || missing_deps+=("${dep}")
   done
 
   if [[ "${#missing_deps[@]}" -gt 0 ]]; then
-    tput setaf 1
-    echo -e '\nThis script has unmet dependencies. You need to install these first:'
-    printf '  %s\n' "${missing_deps[@]}"
-    tput sgr0
+    echo 'Missing required tools:' >&2
+    printf '  %s\n' "${missing_deps[@]}" >&2
     exit 1
   fi
 }
diff --git a/ringtonemaker b/ringtonemaker
--- a/ringtonemaker
+++ b/ringtonemaker
@@ -3,10 +3,16 @@
 readonly program="$(basename "${0}")"
 
 function depends_on {
-  local -r dep="${1}"
+  local -r all_deps=("${@}")
+  local missing_deps=()
 
-  if ! command -v "${dep}" &>/dev/null; then
-    echo -e >&2 "\n$(tput setaf 1)This script requires ${dep}. Please install it first.$(tput sgr0)\n"
+  for dep in "${all_deps[@]}"; do
+    command -v "${dep}" &>/dev/null || missing_deps+=("${dep}")
+  done
+
+  if [[ "${#missing_deps[@]}" -gt 0 ]]; then
+    echo 'Missing required tools:' >&2
+    printf '  %s\n' "${missing_deps[@]}" >&2
     exit 1
   fi
 }
